services:
  todoapp-postgres:
    image: postgres:18.3-alpine
    container_name: todoapp-env-postgres
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    volumes:
      - ./out/pgdata:/var/lib/postgresql
    restart: always

  todoapp-postgres-migrate:
    image: migrate/migrate:4
    volumes:
      - ./migrations:/migrations

  port-forwarder:
    image: alpine/socat:1.8.0.3
    container_name: todoapp-postgres-port-forwarder
    command: tcp-listen:5432,fork,reuseaddr tcp-connect:todoapp-postgres:5432
    ports:
      - "127.0.0.1:5432:5432"
    depends_on:
      - todoapp-postgres